routes/backend.php
<?php

/*
|--------------------------------------------------------------------------
| Backend Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use \Illuminate\Support\Facades\Route;

Route::middleware('backend')->namespace('\Auth')->group(function (){

    Route::get('/', 'LoginController@showLoginForm')->name('admin.login');
    Route::get('/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'LoginController@login')->name('admin.login');
    Route::post('/logout', 'LoginController@logout')->name('admin.logout');

});

Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
Route::get('dashboard/new', 'DashboardController@newele')->name('admin.dashboard.new');

Route::prefix('user')->group(function (){
    Route::get('', 'UserController@index')->name('admin.user.index');
    Route::get('{userid}/profile', 'UserController@profile')->name('admin.user.profile');
    Route::post('{userid}/profile', 'UserController@profileSave')->name('admin.user.profile.save');
    Route::get('{userid}/password', 'UserController@password')->name('admin.user.password');
    Route::post('{userid}/password', 'UserController@passwordSave')->name('admin.user.password.save');
    Route::get('{userid}/trackings', 'UserController@trackings')->name('admin.user.trackings');
    Route::get('{userid}/contacts', 'UserController@contacts')->name('admin.user.contacts');

    Route::get('{userid}/delete', 'UserController@delete')->name('admin.user.delete');
});

Route::prefix('member')->group(function (){
    Route::get('', 'MembersController@index')->name('admin.member.index');
    Route::get('{memberid}/profile', 'MembersController@profile')->name('admin.member.profile');
    Route::post('{memberid}/profile', 'MembersController@profileSave')->name('admin.member.profile.save');
});

Route::prefix('content')->group(function (){
    Route::get('content', 'ContentController@showAll')->name('admin.content');
    Route::get('content/add', 'ContentController@add')->name('admin.content.add');
    Route::post('content/add', 'ContentController@addSave')->name('admin.content.add.save');
    Route::get('content/{contentid}/edit', 'ContentController@edit')->name('admin.content.edit');
    Route::post('content/{contentid}/edit', 'ContentController@editSave')->name('admin.content.edit.save');
});

Route::prefix('tracking')->group(function (){
    Route::get('', 'TrackingController@showAll')->name('admin.tracking');
    Route::get('{trackingid}/info', 'TrackingController@showInfo')->name('admin.tracking.info');
    Route::get('{trackingid}/info/end', 'TrackingController@ende')->name('admin.tracking.end');
    Route::get('{trackingid}/info/route', 'TrackingController@showRoute')->name('admin.tracking.route');

    Route::get('{trackingid}/info/media/', 'TrackingController@showMedia')->name('admin.tracking.info.media');
    Route::post('{trackingid}/info/ajaxmedia/', 'TrackingController@showMediaAjax')->name('admin.tracking.info.mediaajax');
    Route::get('media/show/{path}', 'TrackingController@loadMedia')->name('admin.load.media');

});

Route::prefix('license')->group(function (){
    Route::get('list', 'LicenseController@list')->name('admin.license.list');
    Route::get('add', 'LicenseController@add')->name('admin.license.add');
    Route::post('add', 'LicenseController@addSave')->name('admin.license.add.save');
});

Route::delete('delete/trackings/{trackingid}', 'ControlController@deleteTrackings')->name('api.delete.trackings');
Route::delete('delete/emergencies/{emergencyid}', 'ControlController@deleteEmergencies')->name('api.delete.emergencies');
Route::delete('delete/user/{userid}', 'ControlController@deleteUsers')->name('api.delete.user');


// Notifications
Route::post('notifications', 'NotificationController@store');
Route::get('notifications', 'NotificationController@index');
Route::patch('notifications/{id}/read', 'NotificationController@markAsRead');
Route::post('notifications/mark-all-read', 'NotificationController@markAllRead');
Route::post('notifications/{id}/dismiss', 'NotificationController@dismiss');
// Push Subscriptions
Route::post('subscriptions', 'PushSubscriptionController@update');
Route::post('subscriptions/delete', 'PushSubscriptionController@destroy');
// Manifest file (optional if VAPID is used)
Route::get('manifest.json', function () {
    return [
        'name' => config('app.name'),
        'gcm_sender_id' => config('webpush.gcm.sender_id')
    ];
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Media.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\URL;

class Media extends Model
{
    protected $table = 'media';

    protected $fillable = [
        'Url', 'filename', 'mime', 'size', 'name', 'alt', 'title', 'group', 'status', 'weight'
    ];

    public function mediable() {
        return $this->morphTo()->where('group', 'default');
    }

    public function getUrlAttribute() {
        return URL::asset(config('media.files_directory') . $this->filename);
    }

    public function getTitleAttribute($value) {
        if(empty($value)) {
            return basename($this->attributes['filename']);
        }
        return $value;
    }
}

app/Models/Tracking.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Tracking extends Model
{
    protected $table = 'tracking';

    protected $fillable = [
        'user_id', 'type', 'notify_period', 'delphos', 'status', 'update_countdown', 'friendinfo'
    ];

    protected $dates = [
        'created_at', 'updated_t'
    ];

    public function user(){
        return $this->hasOne(User::class, 'id', 'user_id');
    }

    public function userprofile(){
        return $this->hasOne(UserProfile::class, 'user_id', 'user_id');
    }

    public function route(){
        return $this->hasOne(Route::class, 'tracking_id', 'id');
    }

    public function emergency(){
        return $this->hasOne(Emergency::class, 'tracking_id', 'id');
    }

    public function position(){
        return $this->hasMany(Position::class, 'tracking_id', 'id');
    }

    public function trackingContact(){
        return $this->hasMany(ContactTracking::class, 'tracking_id', 'id');
    }

    public function contacts(){
        return $this->hasManyThrough(Contacts::class, ContactTracking::class, 'tracking_id', 'id', 'id', 'contact_id');
    }

    public function alive(){
        return $this->hasMany(ClientAlive::class, 'tracking_id', 'id');
    }

    public function battery(){
        return $this->hasMany(TrackingPhoneBattery::class, 'tracking_id', 'id');
    }

}

app/Http/Controllers/Api/TrackingController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Resources\TrackingResource;
use App\Models\ClientAlive;
use App\Models\Contacts;
use App\Models\ContactTracking;
use App\Models\Position;
use App\Models\TrackingStartedNotification;
use App\Models\PushNotification;
use App\Models\Tracking;
use App\Models\Route;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Validator;

class TrackingController extends Controller
{
    public function getCurrentTracking(){

        /** @var User $authUser */
        $authUser = Auth::guard('api')->user();

        if ($authUser->activeTracking){

            return new TrackingResource($authUser->activeTracking);
        }

        return Response::json([
            'message' => 'No active Tracking'
        ], 404);

    }

    public function cancelTracking($trackingid){

        $authUser = Auth::guard('api')->user();

        $Tracking = Tracking::find($trackingid);

        $contactid = Contacts::where('sender_id', $Tracking->user_id)->where('recipient_id', $authUser->id)->pluck('id');
        $Tracking->trackingContact()->where('contact_id', $contactid)->where('tracking_id', $trackingid)->update(['cancelled' => true]);

        $pushnotification = PushNotification::where('user_id', $Tracking->user_id)->first();

        if ($pushnotification){
            $push = new \Edujugon\PushNotification\PushNotification('apn');
            $push->setMessage([
                'aps' => [
                    'alert' => [
                        'title' => 'Guarding abgebrochen',
                        'body' =>  $authUser->profile->firstname . ' hat aufgehört dich zu tracken.'
                    ],
                    'sound' => 'default',
                    'badge' => 1,
                ],
            ])
                ->setDevicesToken($pushnotification->device_id)
                ->send();

            $notification = TrackingStartedNotification::where('tracking_id', $trackingid)->get();

            if ($notification){
                foreach ($notification as $value){
                    $value->update([
                        'active' => false
                    ]);
                }
            }

        }

        return Response::json([
            'message' => 'success',
        ], 200);
    }

    public function deny($trackingid){

        $authUser = Auth::guard('api')->user();

        /** @var Tracking $Tracking */
        $Tracking = Tracking::find($trackingid);

        if (!$Tracking){
            return Response::json([
                'message' => 'Tracking not found',
            ], 404);
        }

        $notification = TrackingStartedNotification::where('tracking_id', $trackingid)
            ->where('requested_user_id', $authUser->id)->first();

        if($notification){
            $notification->update(['active' => false]);
        }

        //$Trackings = Tracking::where('delphos', 0)->where('emergency', 0)->where('status', 0)->where('friendinfo', 0)->get();
        $toDo = $Tracking->trackingContact()->count();

        $contact = Contacts::where('sender_id', $Tracking->user_id)->where('recipient_id', $authUser->id)->first();
        $Tracking->trackingContact()->where('contact_id', $contact->id)->where('tracking_id', $trackingid)->update(['cancelled' => true]);

        $pushnotification = PushNotification::where('user_id', $Tracking->user_id)->first();

        if ($pushnotification){
            if($toDo == 1){
                $Tracking->friendinfo = 1;
                $Tracking->update();

                $push = new \Edujugon\PushNotification\PushNotification('apn');
                $push->setMessage([
                    'aps' => [
                        'alert' => [
                            'title' => 'Guarding abgelehnt',
                            'body' =>  $authUser->profile->firstname . ' kann für den Zeitraum leider nicht dein Guard sein.'
                        ],
                        'sound' => 'default',
                        'badge' => 1,
                        'category' => 'delphos.noguards'
                    ],
                ])
                    ->setDevicesToken($pushnotification->device_id)
                    ->send();
            }else{
                $push = new \Edujugon\PushNotification\PushNotification('apn');
                $push->setMessage([
                    'aps' => [
                        'alert' => [
                            'title' => 'Guarding abgelehnt',
                            'body' =>  $authUser->profile->firstname . ' kann für den Zeitraum leider nicht dein Guard sein.'
                        ],
                        'sound' => 'default',
                        'badge' => 1
                    ],
                ])
                    ->setDevicesToken($pushnotification->device_id)
                    ->send();
            }
        }
        return Response::json([
            'message' => 'Success'
        ], 200);
    }

    public function accept($trackingid){

        $authUser = Auth::guard('api')->user();

        /** @var Tracking $Tracking */
        $Tracking = Tracking::find($trackingid);
        if (!$Tracking){
            return Response::json([
                'message' => 'Tracking not found',
            ], 404);
        }

        $notification = TrackingStartedNotification::where('tracking_id', $trackingid)
            ->where('requested_user_id', $authUser->id)->first();

        if($notification){
            $notification->update(['active' => false]);
        }

        /** @var Contacts $contact */
        $contact = Contacts::where('sender_id', $Tracking->user_id)->where('recipient_id', $authUser->id)->first();
        $Tracking->trackingContact()->where('contact_id', $contact->id)->where('tracking_id', $trackingid)->update(['accepted' => true]);

        if($Tracking->status = 'inactive'){

            $Tracking->update(['update_countdown' => Carbon::now()->addMinutes($Tracking->notify_period)->addSeconds(20)->format('Y-m-d H:i:s')]);

        }

        $Tracking->update(['status' => 'active']);

        $pushnotification = PushNotification::where('user_id', $Tracking->user_id)->first();

        if ($pushnotification){
            $push = new \Edujugon\PushNotification\PushNotification('apn');
            $push->setMessage([
                'aps' => [
                    'alert' => [
                        'title' => 'Guarding angenommen',
                        'body' =>  $authUser->profile->firstname . ' hat deine Anfrage als Guard angenommen.'
                    ],
                    'sound' => 'default',
                    'badge' => 1,
                    'category' => 'delphos.guard.start'
                ],
            ])
                ->setDevicesToken($pushnotification->device_id)
                ->send();
        }

        return Response::json([
            'message' => 'Success',
        ], 200);
    }

    public function alive()
    {
        $authUser = Auth::guard('api')->user();

        ClientAlive::create([
            'user_id' => $authUser->id,
            'tracking_id' => $authUser->activeTracking->id,
        ]);

        Tracking::find($authUser->activeTracking->id)
            ->update(['update_countdown' => Carbon::now()->addMinutes(1)->addSeconds(20)->format('Y-m-d H:i:s')]);

        return Response::json([
            'message' => 'Success',
        ], 200);
    }

    public function showHistory()
    {
        $authUser = Auth::guard('api')->user();
        if ($authUser->contacts){
            $contacts = $authUser->iscontact()->pluck('id');
            $trackingids = ContactTracking::whereIn('contact_id', $contacts)->pluck('tracking_id');
            $trackings = Tracking::whereIn('id', $trackingids)->orderBy('created_at', 'DESC')->get();
        }

        $Trackings = $authUser->trackings;

        if ($trackings){
            $concatenated = $Trackings->concat($trackings);
        }

        return TrackingResource::collection($concatenated->sortByDesc('id'));
    }

    public function startTracking(Request $request)
    {
        $v = Validator::make($request->all(), [
            'notify_period' => 'required|numeric',
            'from_location.lat' => '',
            'from_location.lng' => '',
            'to_location.lat' => '',
            'to_location.lng' => '',
            'delphos' => 'boolean',
            'contacts' => 'array'
        ]);

        if ($v->fails()) {
            return Response::json([
                'message' => $v->messages(),
            ], 404);
        } else {

            $authUser = Auth::guard('api')->user();
            $exist = Tracking::where('user_id', $authUser->id)->where('status', "inaktiv")->first();

            if ($exist){
               return Response::json([
                   'message' => 'Already tracking.',
               ], 404);
           }

            $Tracking = new Tracking();
            $Tracking->user_id = $authUser->id;
            $Tracking->notify_period = $request->input('notify_period');

            $Tracking->status = 'inactive';

            if ($request->input('delphos') == 1) {
                $Tracking->delphos = 1;
                $Tracking->status = 'active';
            } else {
                $Tracking->delphos = 0;
            }
            if($Tracking->delphos == 1){
                $Tracking->update_countdown = Carbon::now()
                    ->addMinutes($request->input('notify_period'))
                    ->addSeconds(20)
                    ->format('Y-m-d H:i:s');
            }else{
                $Tracking->update_countdown = Carbon::now()
                    ->addMinutes($request->input('notify_period'))
                    ->addMinutes(3)
                    ->addSeconds(20)
                    ->format('Y-m-d H:i:s');
            }

resources/views/backend/pages/tracking/info.blade.php
@extends('backend.layouts.layout')

@section('title', 'Tracking Info')

@section('content-header')
    <section class="content-header">
        <h1>
            Tracking
            <small>{{ $Tracking->userprofile->firstname . ' ' . $Tracking->userprofile->lastname }}</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.dashboard') }}">Dashboard</a></li>
            <li class="active"><a href="{{ route('admin.tracking.info', $Tracking->id) }}"><i class="fa fa-dashboard"></i> Tracking Info</a></li>
        </ol>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <form role="form" class="form-horizontal" method="POST" action="">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">
                                <i class="fa fa-dashboard">&nbsp;</i>
                                Tracking ID: {{ $Tracking->id }} ({{ $Tracking->created_at }})
                            </h3>
                            <div class="pull-right margin-r-5">
                                @if($Tracking->battery()->count() > 0)
                                    @if($Tracking->battery()->get()->last()->battery_state == 'charging' OR $Tracking->battery()->get()->last()->battery_state == 'full')
                                        <div class="flex-center">
                                            <img class="margin-r-5" height="18px" src="{{ asset('Battery_Charging.png') }}" alt="CHARGING">
                                            <span>{{ $Tracking->battery()->get()->last()->battery_lvl }}%</span>
                                        </div>
                                    @else
                                        @if($Tracking->battery()->get()->last()->battery_lvl <= 20)
                                            <div class="flex-center">
                                                <img class="margin-r-5" height="18px" src="{{ asset('Battery_20.png') }}" alt="LOW">
                                                <span>{{ $Tracking->battery()->get()->last()->battery_lvl }}%</span>
                                            </div>
                                        @elseif($Tracking->battery()->get()->last()->battery_lvl <= 80)
                                            <div class="flex-center">
                                                <img class="margin-r-5" height="18px" src="{{ asset('Battery_20_100.png') }}" alt="MEDIUM">
                                                <span>{{ $Tracking->battery()->get()->last()->battery_lvl }}%</span>
                                            </div>
                                        @endif
                                        @if($Tracking->battery()->get()->last()->battery_lvl > 80)
                                            <div class="flex-center">
                                                <img class="margin-r-5" height="18px" src="{{ asset('Battery_Full.png') }}" alt="FULL">
                                                <span>{{ $Tracking->battery()->get()->last()->battery_lvl }}%</span>
                                            </div>
                                        @endif
                                    @endif
                                @endif
                            </div>
                            @if($Tracking->route()->count() > 0)
                                <div class="pull-right margin-r-5">
                                    <a href="{{ route('admin.tracking.route', $Tracking->id) }}" class="btn btn-xs btn-info">
                                        <i class="fa fa-medium">&nbsp;</i>
                                        Route anzeigen
                                    </a>
                                </div>
                            @endif
                        </div>
                        <div class="box-body">
                            <div class="col-sm-12" style="border-bottom: 1px solid #4b646f; padding-bottom: 20px; margin-bottom: 30px;">
                                @if($Tracking->emergency == 1 && $Tracking->status == 0)
                                    <div class="col-sm-12 text-right">
                                        <a href="{{ route('admin.tracking.end', $Tracking->id) }}" class="btn btn-lg btn-danger">Notfall beenden</a>
                                    </div>
                                @endif
                                <div class="col-sm-2">
                                    <img src="{{ $profilePicture->url or '/img/default-user-img.jpg' }}" alt="ProfilBild" style="width: 100%;">
                                </div>
                                <div class="col-sm-3">
                                    <p  style="font-size: 26px; font-weight: bolder;">
                                        Nutzer:
                                    </p>
                                    <p>
                                        {{ $Tracking->userprofile->firstname}}
                                        {{ $Tracking->userprofile->lastname}} (@if($Tracking->userprofile->height != null) {{$Tracking->userprofile->height}} cm Groß @endif @if($Tracking->userprofile->age != null) {{$Tracking->userprofile->age}} Jahre @endif , @if($Tracking->userprofile->gender == "male") männlich @else weiblich  @endif )
                                    </p>
                                    <p>
                                        Telefon: {{ $Tracking->userprofile->phone or "" }}</p>
                                    <p>
                                        Adresse: {{ $Tracking->userprofile->street . ', ' . $Tracking->userprofile->zip . ' ' . $Tracking->userprofile->city }}</p>
                                </div>
                                <div class="col-sm-3">
                                    <p  style="font-size: 26px; font-weight: bolder;">
                                        Weitere Informationen:
                                    </p>
                                    Unverträglichkeiten: {{$Tracking->userprofile->intolerances}}<br>
                                    Vorerkrankungen: {{$Tracking->userprofile->pre_existing_conditions}}<br>
                                    Medikation: {{$Tracking->userprofile->medication}}<br>
                                    Blutgruppe: {{$Tracking->userprofile->blood_type}}<br>
                                </div>
                                {{--
                                <div class="col-sm-3">
                                    <p  style="font-size: 26px; font-weight: bolder;">
                                        Medien:
                                    </p>
                                    <ul class="medias">
                                        @if($Tracking->emergency()->count() > 0)
                                            @if($Tracking->emergency()->first()->files()->count() > 0)
                                                @foreach($Tracking->emergency()->first()->files()->orderByDesc("id")->limit(5)->get() as $file)
                                                    <li>
                                                        <a href="javascript:void(0);" data-video="/admin/tracking/media/show/{{$file->id}}" class="file">
                                                            {{$file->created_at->format("d.m H:i:s")}}
                                                        </a>
                                                    </li>
                                                @endforeach
                                            @endif
                                        @endif
                                    </ul>
                                </div>--}}
                            </div>


                                <div class="col-sm-12">
                                    <div class="col-sm-6" style="margin-bottom: 30px;">
                                        <div id="map"></div>
                                    </div>
                                    <div class="col-sm-6 player" style="margin-bottom: 30px;">
                                        @if($Tracking->emergency == 1 && $Tracking->status == 0)
                                            <a href="javascript:void(0);" class="btn btn-success" style="width:300px;font-size:30px;margin:auto;" >Stream starten</a>
                                            <div class="iframe"></div>
                                        @endif
                                    </div>
                                </div>

                        </div>
                        <div class="box-footer">

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
@endsection
@section('template_linked_css')
    <style>
        #map {
            height: 700px;
            width: 100%;
        }

        .flex-center{
            display: flex;
            justify-content: center;
            align-items: center;
        }
    </style>
@endsection
@section('template_linked_js')


<script>
    $(".player").click(function(){
        $(".player a").hide();
        $(".iframe").html("<iframe src='/stream.php?user=37' style='width:420px; height: 320px; border: 0px;'></iframe>");
    });

    var marker = "";
    @if(!empty($position->lat))
    function initMap() {
        var uluru = {lat: {{ $position->lat or null }}, lng: {{ $position->lng or null }}};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 17,
            center: uluru
        });
        marker = new google.maps.Marker({
            position: uluru,
            map: map
        });
    }
    @else
    function initMap() {
        var uluru = {lat: {{ $Tracking->emergency()->first()->lat or null }}, lng: {{ $Tracking->emergency()->first()->lng or null }}};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 17,
            center: uluru
        });
        marker = new google.maps.Marker({
            position: uluru,
            map: map
        });
    }
    @endif

    $( document ).ready(function() {


        window.setInterval(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}"
                }
            });

            $.ajax({
                method: "POST",
                url: "/admin/tracking/{{ $Tracking->id }}/info/ajaxmedia",
            }).done(function( data ) {
                $(".medias").html(data.message);
                var lat = parseFloat(data.lat);
                var lng = parseFloat(data.lng);
                var newLatLng = new google.maps.LatLng(lat, lng);
                marker.setPosition(newLatLng);
            }).fail(function( ) {

            });
        }, 5000);

        $(document).on('click','.file',function(){
             var data = $(this).data("video");
             $(".player").html('<video  style="height: 500px;width: 100%;" controls autoplay> <source src="'+data+'"> </video>');
         });

    });
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCKA1xP97auygGzcFXg0Ql6dK64Cf07WO4&callback=initMap">
</script>
@endsection